baseURL = "http://blog.fortizabril.com"
languageCode = "en-us"
title = "Fran Ortiz's Blog"
theme = "ananke"
googleAnalytics = "UA-107502336-1"

[params]
  favicon = ""
  description = "Personal blog of Fran Ortiz"
  facebook = ""
  twitter = "https://twitter.com/Fortiz2305"
  instagram = ""
  youtube = ""
  github = "https://github.com/Fortiz2305"
  linkedin = "https://www.linkedin.com/in/francisco-ortiz-abril/"
  background_color_class = "bg-blue"
  featured_image = "/images/Blog_Containers_header.png"

[taxonomies]
  tag = "tags"
