baseURL = "http://blog.fortizabril.com"
languageCode = "en-us"
title = "Blog de Francisco Ortiz"
theme = "gohugo-theme-ananke"
googleAnalytics = "UA-107502336-1"

[params]
  favicon = ""
  description = ""
  facebook = ""
  twitter = "https://twitter.com/Fortiz2305"
  instagram = ""
  youtube = ""
  github = "https://github.com/Fortiz2305"
  linkedin = "https://www.linkedin.com/in/francisco-ortiz-abril/"
  # choose a background color from any on this page: http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-blue"
  featured_image = "/images/Blog_Containers_header.png"

[taxonomies]
  tag = "tags"
